#!/usr/bin/python

# -*- coding: UTF-8 -*-# enable debugging

import git
import cgitb
import string

cgitb.enable()



repo = git.Repo('/var/www/test/python-ciscoconfig')
commits = list(repo.iter_commits("master"))
print "Content-type: text/html\n\n";


print("""<html>

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Test</title>

</head>

<body>

    <h1>Test</h1>

    <select name="" id="">""")


for i in commits:

  print('<option value=' + str(i.hexsha) + '>' + str(i.message) + str( i.committed_datetime) +'</option>')

print("""    </select>

</body>

</html>
""")

